spring:
  application:
    name: gateway
  profiles:
    active: default

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clans_service
          uri: lb://test
          predicates:
            - Path=/api/v1/tests/**
server:
  port: 2020

#Eureka confing
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/