spring:
  application:
    name: gateway
  profiles:
    active: default

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clans_service
          uri: http://192.168.20.19:14700
          predicates:
            - Path=/api/v1/tests/**
server:
  port: 2020

#Eureka confing
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/